# Generated by Django 3.2.3 on 2021-08-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210811_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='size',
            new_name='vehicle_class',
        ),
    ]
