# Generated by Django 3.2.3 on 2021-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_apt_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_null.png', null=True, upload_to=''),
        ),
    ]
