# Generated by Django 3.2.3 on 2021-08-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_parkingspace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parkingspace',
        ),
    ]
