# Generated by Django 3.2.3 on 2021-08-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_delete_parkingspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parkingspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_space', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
